// Generated by scripts/generate-demo-transcript.mjs from the real CLI.
// Temporary paths are the only normalized values.
export const demoTranscript = [
  "DEMO HOLD — do not release — 1 expected defect found",
  "  Error [code.flow-changed] Code fence on line 7 is present but its line flow changed",
  "Sample workspace: /tmp/codeproof-demo-…",
  "HTML proof sheet: /tmp/codeproof-demo-…/proof/index.html"
] as const;
